# Generated by Django 4.0.4 on 2022-05-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='students',
            name='mobil',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='number',
            field=models.IntegerField(blank=True),
        ),
    ]
