# Generated by Django 4.0.4 on 2022-05-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_students_email_alter_students_mobil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
